/*
 * lvgl_ui_channel.c - Pet UI channel for the AI Agent.
 *
 * Self-contained LVGL display stack for boards WITHOUT a miwear
 * environment: lv_init() + lv_nuttx_init() (framebuffer /dev/lcd0,
 * touch /dev/input0) + a dedicated render thread running
 * lv_timer_handler().
 *
 * UI layout (stage):
 *   - cloud mascot centered (pet_display.c), tap toggles the bubble
 *   - head bubble above the pet showing the latest message
 *   - message menu button (top-right) opens the full history page
 *
 * External interface (init/start/stop/show/send) is unchanged so the
 * agent core (agent_main.c, outbound dispatch) keeps working.
 */

#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <unistd.h>

#include <lvgl/lvgl.h>
#include <lvgl/src/drivers/nuttx/lv_nuttx_entry.h>

#include "voice/voice_channel.h"
#include "pet_display.h"
#include "pet_page.h"
#include "launcher_page.h"

/* Custom CJK subset font (generated by tools/gen_cjk_font.sh) */
extern const lv_font_t ui_font_cjk_18;

#define UI_TAG       "lvgl_ui"
#define RENDER_PERIOD_US 5000
#define RENDER_STACK 32768

#define MSG_MAX_LEN  512
#define CHAT_HISTORY_MAX 20

#define BUBBLE_RADIUS   14
#define BUBBLE_PAD_X    14
#define BUBBLE_PAD_Y    10
#define BUBBLE_MAX_W    330
#define BUBBLE_TAIL     14
#define BUBBLE_TOP_Y    70    /* keep clear of the top edge (panel bezel) */
#define BUBBLE_MAX_CHARS 132   /* head bubble shows at most ~3 lines */
#define PET_SIZE        300

/* Colors */
#define CLR_BG         0x1a1a2e   /* deep navy background */
#define CLR_PANEL      0x232347   /* bubble / button background */
#define CLR_BUBBLE_USER 0x3a5cff  /* user bubble */
#define CLR_BUBBLE_PET 0x2e2e55   /* pet bubble */
#define CLR_TEXT       0xe8e8f0
#define CLR_TEXT_DIM   0x9a9ab0

/* ── Chat history ring buffer ──────────────────────────────────── */

typedef struct {
    char text[MSG_MAX_LEN];
    bool is_user;
} chat_msg_t;

typedef struct {
    chat_msg_t msgs[CHAT_HISTORY_MAX];
    int head;
    int count;
} chat_history_t;

static chat_history_t s_history;

static void history_add(const char *text, bool is_user)
{
    chat_msg_t *slot = &s_history.msgs[s_history.head];

    memset(slot, 0, sizeof(*slot));
    strncpy(slot->text, text, MSG_MAX_LEN - 1);
    slot->text[MSG_MAX_LEN - 1] = '\0';
    slot->is_user = is_user;

    s_history.head = (s_history.head + 1) % CHAT_HISTORY_MAX;
    if (s_history.count < CHAT_HISTORY_MAX) {
        s_history.count++;
    }
}

int lvgl_ui_history_count(void)
{
    return s_history.count;
}

bool lvgl_ui_history_get(int newest_first, char *buf, size_t len,
                        bool *is_user)
{
    const chat_msg_t *m;
    int idx;

    /* Callers run on the LVGL thread (pet page, history page), the same
     * thread history_add() is reached from via lv_async_call, so the ring
     * needs no lock. */

    if (!buf || len == 0 || newest_first < 0 ||
        newest_first >= s_history.count) {
        return false;
    }

    idx = (s_history.head - 1 - newest_first + 2 * CHAT_HISTORY_MAX)
          % CHAT_HISTORY_MAX;
    m = &s_history.msgs[idx];

    strncpy(buf, m->text, len - 1);
    buf[len - 1] = '\0';
    if (is_user) {
        *is_user = m->is_user;
    }
    return true;
}

/* ── State ─────────────────────────────────────────────────────── */

typedef struct {
    bool initialized;
    bool running;
    pthread_t render_tid;

    lv_obj_t *screen;
    const lv_font_t *font;
    const lv_font_t *font_big;

    lv_obj_t *bubble;          /* head bubble (latest message) */
    lv_obj_t *bubble_label;
    lv_obj_t *bubble_tail;
    lv_obj_t *menu_btn;        /* message menu button, top-right */
    lv_obj_t *history_page;    /* full-screen history page */
    lv_obj_t *history_list;
    bool history_visible;

    bool bubble_visible;
    bool welcome_shown;
} ui_state_t;

static ui_state_t s_ui;

/* ── Forward declarations ──────────────────────────────────────── */

static void history_btn_cb(lv_event_t *e);
static void history_rebuild_list(void);

/* Timer helper: return the pet to idle after a moment */
static void pet_back_idle_timer_cb(lv_timer_t *timer)
{
    lv_timer_delete(timer);
    pet_display_set_emotion(PET_EMOTION_IDLE);
}

static void pet_back_idle_after(uint32_t ms)
{
    lv_timer_create(pet_back_idle_timer_cb, ms, NULL);
}

/* ── Async message passing (agent threads -> LVGL thread) ──────── */

typedef struct {
    char text[MSG_MAX_LEN];
    bool is_user;
} ui_msg_t;

/* Set the bubble text, truncated so the bubble stays short enough to
 * fully fit below the screen top edge. */
static void bubble_set_text(const char *text)
{
    char buf[BUBBLE_MAX_CHARS + 4];
    size_t len;
    size_t cut = BUBBLE_MAX_CHARS;

    if (text == NULL) {
        lv_label_set_text(s_ui.bubble_label, "");
        return;
    }
    len = strlen(text);
    if (len <= BUBBLE_MAX_CHARS) {
        lv_label_set_text(s_ui.bubble_label, text);
        return;
    }
    /* back off to a UTF-8 char boundary so the cut is clean */
    while (cut > 0 && ((unsigned char)text[cut] & 0xC0) == 0x80) {
        cut--;
    }
    memcpy(buf, text, cut);
    memcpy(buf + cut, "\xe2\x80\xa6", 4); /* … */
    lv_label_set_text(s_ui.bubble_label, buf);
}

static void bubble_update_async_cb(void *data)
{
    ui_msg_t *m = (ui_msg_t *)data;

    if (!s_ui.initialized || !s_ui.running) {
        free(m);
        return;
    }

    history_add(m->text, m->is_user);
    bubble_set_text(m->text);
    /* AI reply text also lands in the pet page text layer (no-op when
     * the page is not open); user words never overwrite the greeting. */
    if (!m->is_user) {
        pet_page_update_response(m->text);
    }
    /* keep the launcher pet page bubble in sync (no-op when not created) */
    lv_obj_set_style_bg_color(s_ui.bubble,
                              m->is_user ? lv_color_hex(CLR_BUBBLE_USER)
                                         : lv_color_hex(CLR_BUBBLE_PET), 0);
    lv_obj_set_style_bg_color(s_ui.bubble_tail,
                              m->is_user ? lv_color_hex(CLR_BUBBLE_USER)
                                         : lv_color_hex(CLR_BUBBLE_PET), 0);

    /* Rebuild the history page list if it is open */
    if (s_ui.history_visible) {
        lv_obj_clean(s_ui.history_list);
        history_rebuild_list();
    }

    free(m);
}

/* ── Emotion helper (reply text -> pet emotion) ────────────────── */

static pet_emotion_t emotion_from_text(const char *text)
{
    if (text == NULL) {
        return PET_EMOTION_SPEAKING;
    }
    if (strstr(text, "？") || strstr(text, "?") ||
        strstr(text, "怎么") || strstr(text, "为什么")) {
        return PET_EMOTION_CONFUSED;
    }
    if (strstr(text, "哈哈") || strstr(text, "开心") ||
        strstr(text, "棒") || strstr(text, "爱") ||
        strstr(text, "❤")) {
        return PET_EMOTION_HAPPY;
    }
    return PET_EMOTION_SPEAKING;
}

/* ── Bubble show/hide ──────────────────────────────────────────── */

static void bubble_hide_anim_cb(lv_anim_t *a)
{
    lv_obj_add_flag(s_ui.bubble, LV_OBJ_FLAG_HIDDEN);
    s_ui.bubble_visible = false;
    (void)a;
}

static void bubble_show_anim(void)
{
    lv_obj_remove_flag(s_ui.bubble, LV_OBJ_FLAG_HIDDEN);
    lv_anim_t a;

    lv_anim_init(&a);
    lv_anim_set_var(&a, s_ui.bubble);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&a, BUBBLE_TOP_Y + 8, BUBBLE_TOP_Y);
    lv_anim_set_time(&a, 260);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_start(&a);

    s_ui.bubble_visible = true;
}

static void bubble_hide_anim(void)
{
    lv_anim_t a;

    lv_anim_init(&a);
    lv_anim_set_var(&a, s_ui.bubble);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&a, BUBBLE_TOP_Y, BUBBLE_TOP_Y - 10);
    lv_anim_set_time(&a, 200);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_in);
    lv_anim_set_deleted_cb(&a, bubble_hide_anim_cb);
    lv_anim_start(&a);
}

/* ── History page ──────────────────────────────────────────────── */

static lv_obj_t *history_bubble_create(lv_obj_t *parent, const char *text,
                                       bool is_user)
{
    lv_obj_t *row = lv_obj_create(parent);
    lv_obj_set_size(row, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_style_bg_opa(row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(row, 0, 0);
    lv_obj_set_style_pad_all(row, 4, 0);
    lv_obj_set_flex_flow(row, is_user ? LV_FLEX_FLOW_ROW : LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_t *b = lv_obj_create(row);
    lv_obj_set_size(b, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_style_radius(b, BUBBLE_RADIUS, 0);
    lv_obj_set_style_bg_color(b, lv_color_hex(is_user ? CLR_BUBBLE_USER
                                                      : CLR_BUBBLE_PET), 0);
    lv_obj_set_style_border_width(b, 0, 0);
    lv_obj_set_style_pad_all(b, 0, 0);
    lv_obj_set_style_pad_left(b, BUBBLE_PAD_X, 0);
    lv_obj_set_style_pad_right(b, BUBBLE_PAD_X, 0);
    lv_obj_set_style_pad_top(b, BUBBLE_PAD_Y, 0);
    lv_obj_set_style_pad_bottom(b, BUBBLE_PAD_Y, 0);

    lv_obj_t *lbl = lv_label_create(b);
    lv_label_set_text(lbl, text);
    lv_label_set_long_mode(lbl, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(lbl, BUBBLE_MAX_W - 2 * BUBBLE_PAD_X);
    lv_obj_set_style_text_font(lbl, s_ui.font, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(CLR_TEXT), 0);
    lv_obj_set_style_text_line_space(lbl, 2, 0);

    return row;
}

static void history_rebuild_list(void)
{
    int i;
    int idx = s_history.head;
    chat_msg_t *m;

    if (!s_ui.history_list) {
        return;
    }

    lv_obj_clean(s_ui.history_list);
    for (i = 0; i < s_history.count; i++) {
        idx = (idx + CHAT_HISTORY_MAX - 1) % CHAT_HISTORY_MAX;
        m = &s_history.msgs[idx];
        history_bubble_create(s_ui.history_list, m->text, m->is_user);
    }
    lv_obj_scroll_to_y(s_ui.history_list, LV_COORD_MAX, LV_ANIM_OFF);
}

static void history_page_toggle(void)
{
    if (s_ui.history_visible) {
        lv_obj_add_flag(s_ui.history_page, LV_OBJ_FLAG_HIDDEN);
        s_ui.history_visible = false;
        return;
    }
    history_rebuild_list();
    lv_obj_move_foreground(s_ui.history_page);
    lv_obj_remove_flag(s_ui.history_page, LV_OBJ_FLAG_HIDDEN);
    s_ui.history_visible = true;
}

/* ── Pet tap: toggle the head bubble ───────────────────────────── */

static void pet_click_cb(lv_event_t *e)
{
    (void)e;

    if (s_ui.bubble_visible) {
        bubble_hide_anim();
        pet_display_set_emotion(PET_EMOTION_IDLE);
    } else {
        if (!s_ui.welcome_shown) {
            bubble_set_text(
                "\xe4\xbd\xa0\xe5\xa5\xbd\xe5\x91\x80\xef\xbc\x8c\xe6\x88\x91"
                "\xe6\x98\xaf\xe5\xb0\x8f\xe4\xba\x91\xef\xbc\x8c\xe7\x82\xb9"
                "\xe5\x87\xbb\xe6\x88\x91\xe5\xbc\x80\xe5\xa7\x8b\xe8\xaf\xb4"
                "\xe8\xaf\x9d\xef\xbd\x9e"); /* 你好呀，我是小云，点击我开始说话～ */
            s_ui.welcome_shown = true;
        }
        bubble_show_anim();
        pet_display_set_emotion(PET_EMOTION_ACTIVE);
        pet_back_idle_after(700);
    }
}

/* ── Widget creation (LVGL thread only) ────────────────────────── */

static lv_obj_t *bubble_widget_create(void)
{
    lv_obj_t *bubble;
    lv_obj_t *lbl;
    lv_obj_t *tail;
    int W = lv_display_get_horizontal_resolution(NULL);
    int H = lv_display_get_vertical_resolution(NULL);
    int bw = (W - 60 < BUBBLE_MAX_W) ? W - 60 : BUBBLE_MAX_W;

    bubble = lv_obj_create(s_ui.screen);
    lv_obj_set_size(bubble, bw, LV_SIZE_CONTENT);
    lv_obj_align(bubble, LV_ALIGN_TOP_MID, 0, BUBBLE_TOP_Y);
    lv_obj_set_style_radius(bubble, BUBBLE_RADIUS, 0);
    lv_obj_set_style_bg_color(bubble, lv_color_hex(CLR_BUBBLE_PET), 0);
    lv_obj_set_style_border_width(bubble, 0, 0);
    lv_obj_set_style_pad_all(bubble, 0, 0);
    lv_obj_set_style_pad_left(bubble, BUBBLE_PAD_X, 0);
    lv_obj_set_style_pad_right(bubble, BUBBLE_PAD_X, 0);
    lv_obj_set_style_pad_top(bubble, BUBBLE_PAD_Y, 0);
    lv_obj_set_style_pad_bottom(bubble, BUBBLE_PAD_Y + BUBBLE_TAIL, 0);
    lv_obj_set_style_shadow_width(bubble, 0, 0);
    lv_obj_add_flag(bubble, LV_OBJ_FLAG_HIDDEN);

    lbl = lv_label_create(bubble);
    lv_label_set_long_mode(lbl, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(lbl, bw - 2 * BUBBLE_PAD_X);
    lv_obj_set_style_text_font(lbl, s_ui.font, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(CLR_TEXT), 0);
    lv_obj_set_style_text_line_space(lbl, 2, 0);

    /* bubble tail: small rotated square pointing at the pet */
    tail = lv_obj_create(bubble);
    lv_obj_set_size(tail, BUBBLE_TAIL, BUBBLE_TAIL);
    lv_obj_align(tail, LV_ALIGN_BOTTOM_MID, 0, -(BUBBLE_TAIL / 2));
    lv_obj_set_style_bg_color(tail, lv_color_hex(CLR_BUBBLE_PET), 0);
    lv_obj_set_style_border_width(tail, 0, 0);
    lv_obj_set_style_radius(tail, 2, 0);
    lv_obj_set_style_transform_rotation(tail, 450, 0);
    lv_obj_set_style_transform_pivot_x(tail, BUBBLE_TAIL / 2, 0);
    lv_obj_set_style_transform_pivot_y(tail, BUBBLE_TAIL / 2, 0);

    s_ui.bubble = bubble;
    s_ui.bubble_label = lbl;
    s_ui.bubble_tail = tail;
    (void)H;
    return bubble;
}

static void menu_btn_create(void)
{
    lv_obj_t *btn;
    lv_obj_t *bar;
    int W = lv_display_get_horizontal_resolution(NULL);
    int i;

    btn = lv_obj_create(s_ui.screen);
    lv_obj_set_size(btn, 60, 60);
    lv_obj_align(btn, LV_ALIGN_TOP_RIGHT, -24, BUBBLE_TOP_Y);
    lv_obj_set_style_radius(btn, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(btn, lv_color_hex(CLR_PANEL), 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_set_style_shadow_width(btn, 0, 0);

    /* three bars = menu glyph (no font dependency) */
    for (i = 0; i < 3; i++) {
        bar = lv_obj_create(btn);
        lv_obj_set_size(bar, 26, 4);
        lv_obj_align(bar, LV_ALIGN_CENTER, 0, (i - 1) * 10);
        lv_obj_set_style_bg_color(bar, lv_color_hex(CLR_TEXT_DIM), 0);
        lv_obj_set_style_border_width(bar, 0, 0);
        lv_obj_set_style_radius(bar, 2, 0);
    }

    lv_obj_add_flag(btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(btn, history_btn_cb, LV_EVENT_CLICKED, NULL);
    s_ui.menu_btn = btn;
    (void)W;
}

static void history_page_create(void)
{
    lv_obj_t *page;
    lv_obj_t *header;
    lv_obj_t *close_btn;
    lv_obj_t *lbl;
    lv_obj_t *list;
    int W = lv_display_get_horizontal_resolution(NULL);
    int H = lv_display_get_vertical_resolution(NULL);

    page = lv_obj_create(s_ui.screen);
    lv_obj_set_size(page, W, H);
    lv_obj_set_pos(page, 0, 0);
    lv_obj_set_style_bg_color(page, lv_color_hex(CLR_BG), 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_style_pad_all(page, 0, 0);
    lv_obj_add_flag(page, LV_OBJ_FLAG_HIDDEN);

    header = lv_obj_create(page);
    lv_obj_set_size(header, lv_pct(100), BUBBLE_TOP_Y + 56);
    lv_obj_set_style_bg_opa(header, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(header, 0, 0);
    lv_obj_set_style_pad_all(header, 0, 0);

    lbl = lv_label_create(header);
    lv_label_set_text(lbl,
        "\xe5\xaf\xb9\xe8\xaf\x9d\xe8\xae\xb0\xe5\xbd\x95"); /* 对话记录 */
    lv_obj_set_style_text_font(lbl, s_ui.font_big, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(CLR_TEXT), 0);
    lv_obj_align(lbl, LV_ALIGN_CENTER, 0, 0);

    close_btn = lv_obj_create(header);
    lv_obj_set_size(close_btn, 64, 36);
    lv_obj_align(close_btn, LV_ALIGN_TOP_LEFT, 10, BUBBLE_TOP_Y + 10);
    lv_obj_set_style_radius(close_btn, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(close_btn, lv_color_hex(CLR_PANEL), 0);
    lv_obj_set_style_border_width(close_btn, 0, 0);
    lv_obj_add_flag(close_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(close_btn, history_btn_cb, LV_EVENT_CLICKED, NULL);

    lbl = lv_label_create(close_btn);
    lv_label_set_text(lbl, "\xe5\x85\xb3\xe9\x97\xad"); /* 关闭 */
    lv_obj_set_style_text_font(lbl, s_ui.font, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(CLR_TEXT), 0);
    lv_obj_center(lbl);

    list = lv_obj_create(page);
    lv_obj_set_size(list, lv_pct(100), lv_pct(100));
    lv_obj_set_pos(list, 0, BUBBLE_TOP_Y + 56);
    lv_obj_set_style_bg_opa(list, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(list, 0, 0);
    lv_obj_set_style_pad_all(list, 10, 0);
    lv_obj_set_flex_flow(list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(list, 10, 0);
    lv_obj_set_scroll_dir(list, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(list, LV_SCROLLBAR_MODE_OFF);

    s_ui.history_page = page;
    s_ui.history_list = list;
    s_ui.history_visible = false;
}

static void history_btn_cb(lv_event_t *e)
{
    (void)e;
    history_page_toggle();
}

/* ── Render thread ─────────────────────────────────────────────── */

static void ui_build(void)
{
    int W = lv_display_get_horizontal_resolution(NULL);
    int H = lv_display_get_vertical_resolution(NULL);

    syslog(LOG_INFO, "[%s] build UI on %dx%d display\n", UI_TAG, W, H);

    s_ui.screen = lv_screen_active();
    lv_obj_set_style_bg_color(s_ui.screen, lv_color_hex(CLR_BG), 0);

    s_ui.font = &ui_font_cjk_18;
    s_ui.font_big = s_ui.font;

    bubble_widget_create();
    menu_btn_create();
    history_page_create();

    if (pet_display_init(s_ui.screen) != 0) {
        syslog(LOG_ERR, "[%s] pet_display_init failed\n", UI_TAG);
    }

    /* tap the pet to toggle the head bubble */
    lv_obj_add_flag(pet_display_get_obj(), LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(pet_display_get_obj(), pet_click_cb,
                        LV_EVENT_CLICKED, NULL);
    lv_obj_move_foreground(pet_display_get_obj());

    /* Launcher desktop on top: app icons → pet / settings pages */
    launcher_create();
    lv_obj_move_foreground(launcher_desktop_obj());

    /* The desktop is opaque and covers the whole screen, so the pet stage
     * below it can never be seen -- but LVGL culls invalidation only for
     * LV_OBJ_FLAG_HIDDEN objects, never for ones merely covered by a sibling.
     * Left visible, the pet's idle float animation invalidated its 300x300
     * area every refresh period and dragged a full-screen repaint with it.
     * Also hide the menu button for the same reason.
     */

    pet_display_set_stage_visible(false);
    if (s_ui.menu_btn) {
        lv_obj_add_flag(s_ui.menu_btn, LV_OBJ_FLAG_HIDDEN);
    }

    syslog(LOG_INFO, "[%s] launcher desktop created\n", UI_TAG);
}

/* ── Render thread ─────────────────────────────────────────────── */

static void *render_thread(void *arg)
{
    (void)arg;

    ui_build();

    while (s_ui.running) {
        lv_timer_handler();
        usleep(RENDER_PERIOD_US);
    }
    return NULL;
}

/* ── External interface ────────────────────────────────────────── */

#define DEV_WAIT_STEP_US  50000
#define DEV_WAIT_STEPS    60

static void wait_for_device(const char *path)
{
    int i;

    /* Both /dev/lcd0 and /dev/input0 come from the board's asynchronous
     * LCD/touch bringup thread, which can still be running when we get here.
     * lv_nuttx_init() probes each path exactly once and gives up on ENOENT,
     * which used to leave the UI display-only on roughly half the boots.
     */

    for (i = 0; i < DEV_WAIT_STEPS; i++) {
        if (access(path, F_OK) == 0) {
            return;
        }
        usleep(DEV_WAIT_STEP_US);
    }

    syslog(LOG_WARNING, "[%s] %s never appeared\n", UI_TAG, path);
}

int lvgl_ui_channel_init(void)
{
    lv_nuttx_result_t result;
    lv_nuttx_dsc_t info;

    if (s_ui.initialized) {
        return 0;
    }

    syslog(LOG_INFO, "[%s] init\n", UI_TAG);

    wait_for_device(CONFIG_AI_AGENT_LCD_PATH);
    wait_for_device(CONFIG_AI_AGENT_TOUCH_PATH);

    lv_init();
    lv_nuttx_dsc_init(&info);
    info.fb_path = CONFIG_AI_AGENT_LCD_PATH;
    info.input_path = CONFIG_AI_AGENT_TOUCH_PATH;
    lv_nuttx_init(&info, &result);

    if (result.disp == NULL) {
        syslog(LOG_ERR, "[%s] lv_nuttx_init failed (no display)\n", UI_TAG);
        return -EIO;
    }

    s_ui.initialized = true;
    syslog(LOG_INFO, "[%s] init OK\n", UI_TAG);
    return 0;
}

int lvgl_ui_channel_start(void)
{
    int ret;
    pthread_attr_t attr;

    if (!s_ui.initialized) {
        syslog(LOG_ERR, "[%s] start: not initialized\n", UI_TAG);
        return -EINVAL;
    }
    if (s_ui.running) {
        return 0;
    }

    s_ui.running = true;

    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, RENDER_STACK);
    ret = pthread_create(&s_ui.render_tid, &attr, render_thread, NULL);
    pthread_attr_destroy(&attr);
    if (ret != 0) {
        s_ui.running = false;
        syslog(LOG_ERR, "[%s] render thread create failed (%d)\n", UI_TAG, ret);
        return -ret;
    }

    syslog(LOG_INFO, "[%s] started\n", UI_TAG);
    return 0;
}

void lvgl_ui_channel_stop(void)
{
    s_ui.running = false;
    if (s_ui.render_tid) {
        pthread_join(s_ui.render_tid, NULL);
        s_ui.render_tid = 0;
    }
    s_ui.initialized = false;
}

void lvgl_ui_channel_show(void)
{
    /* The pet stage is always visible; show the bubble. */
    if (!s_ui.initialized || !s_ui.running) {
        return;
    }
    /* Reply arrived: if user is on the desktop, open the pet page */
    if (launcher_is_on_desktop()) {
        launcher_enter_page(PAGE_PET);
    }
    if (!s_ui.bubble_visible) {
        bubble_show_anim();
    }
}

/* Bring the pet stage (pet + bubble + menu) to the foreground */
void lvgl_ui_enter_pet_stage(void)
{
    if (!s_ui.initialized || !s_ui.running) {
        return;
    }
    lv_obj_move_foreground(pet_display_get_obj());
    if (s_ui.bubble != NULL) {
        lv_obj_move_foreground(s_ui.bubble);
    }
    if (s_ui.menu_btn != NULL) {
        lv_obj_move_foreground(s_ui.menu_btn);
    }
}

int lvgl_ui_channel_send(const char *text)
{
    ui_msg_t *payload;
    pet_emotion_t emotion;

    if (!text || text[0] == '\0') {
        return -EINVAL;
    }
    if (!s_ui.initialized || !s_ui.running) {
        syslog(LOG_WARNING, "[%s] send: channel not ready\n", UI_TAG);
        return -EINVAL;
    }

    /* schedule the bubble update on the LVGL thread */
    payload = malloc(sizeof(ui_msg_t));
    if (!payload) {
        return -ENOMEM;
    }
    memset(payload, 0, sizeof(*payload));
    strncpy(payload->text, text, MSG_MAX_LEN - 1);
    payload->is_user = false;
    lv_async_call(bubble_update_async_cb, payload);

    /* emotion follows the reply content */
    emotion = emotion_from_text(text);
    if (emotion == PET_EMOTION_SPEAKING) {
        /* TTS is blocking; the pet "speaks" while it plays */
        pet_display_set_emotion(PET_EMOTION_SPEAKING);
        if (voice_channel_speak(text) != 0) {
            syslog(LOG_WARNING, "[%s] voice_channel_speak failed\n", UI_TAG);
        }
        pet_display_set_emotion(PET_EMOTION_IDLE);
    } else {
        pet_display_set_emotion(emotion);
        pet_back_idle_after(1500);
    }

    return 0;
}

/* Public: show a user-side message (called by ASR path, phase B) */
int lvgl_ui_channel_send_user(const char *text)
{
    ui_msg_t *payload;

    if (!text || text[0] == '\0' || !s_ui.initialized || !s_ui.running) {
        return -EINVAL;
    }

    payload = malloc(sizeof(ui_msg_t));
    if (!payload) {
        return -ENOMEM;
    }
    memset(payload, 0, sizeof(*payload));
    strncpy(payload->text, text, MSG_MAX_LEN - 1);
    payload->is_user = true;
    lv_async_call(bubble_update_async_cb, payload);
    return 0;
}

/* Record into the chat ring without touching the bubble or the pet.
 * Used for traffic that never renders as a bubble -- NSH `ask` questions and
 * the replies dispatched back on the "cli" channel -- so the history window
 * shows the whole conversation regardless of which channel carried it. */

static void history_log_async_cb(void *data)
{
    ui_msg_t *m = (ui_msg_t *)data;

    if (s_ui.initialized) {
        history_add(m->text, m->is_user);
        if (s_ui.history_visible) {
            history_rebuild_list();
        }
        /* Replies reaching the ring through this path (NSH `ask`, the Key2
         * demo question) still belong on the pet page text layer -- it is a
         * no-op while that page is closed. */
        if (!m->is_user) {
            pet_page_update_response(m->text);
        }
    }
    free(m);
}

int lvgl_ui_channel_log(const char *text, bool is_user)
{
    ui_msg_t *payload;

    if (!text || text[0] == '\0' || !s_ui.initialized) {
        return -EINVAL;
    }

    payload = malloc(sizeof(ui_msg_t));
    if (!payload) {
        return -ENOMEM;
    }
    memset(payload, 0, sizeof(*payload));
    strncpy(payload->text, text, MSG_MAX_LEN - 1);
    payload->is_user = is_user;
    lv_async_call(history_log_async_cb, payload);
    return 0;
}
