/*
 * pet_display.c - Cloud mascot (pet) display module for the AI Agent UI.
 *
 * The mascot is drawn with LVGL primitives (a rounded body, two bumps, two
 * eyes) instead of from a bitmap: the two 300x300 ARGB8888 frames it used to
 * blend cost 720 KB of flash, which is now spent on the on-device language
 * model.  Emotion layers (question marks, sparkles, blush) and the emotion
 * animations are unchanged; only the eye-blink frames are gone.
 * All widget access happens on the LVGL thread (callers use the
 * lv_async_call wrapper in pet_display_set_emotion()).
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>

#include "pet_display.h"

/* Custom CJK subset font (generated by tools/gen_cjk_font.sh) */
extern const lv_font_t ui_font_cjk_18;

#define PET_SIZE       300
#define PET_BASE_SCALE 256    /* LVGL scale: 256 = 100% */
#define PET_PIVOT_X    150
#define PET_PIVOT_Y    285    /* bottom center, so rotation looks natural */

/* Emotion layer offsets, relative to the pet top-left corner */
#define QMARK_X        150
#define QMARK_Y        -36
#define BLUSH_X1       105
#define BLUSH_X2       200
#define BLUSH_Y        172
#define SPARK_X1       60
#define SPARK_Y1       -20
#define SPARK_X2       250
#define SPARK_Y2       240

#define PET_TAG "pet"

typedef struct {
    bool initialized;
    lv_obj_t *screen;
    lv_obj_t *img;            /* the pet body (drawn, not a bitmap) */
    lv_obj_t *qmark;          /* "？？？" label above the head */
    lv_obj_t *blush[2];       /* pink cheek dots */
    lv_obj_t *spark[2];       /* sparkle dots */
    pet_emotion_t emotion;
    int base_x;               /* pet position when idle */
    int base_y;
    bool layers_visible;
    bool stage_visible;       /* false while the desktop covers the pet */
} pet_state_t;

static pet_state_t s_pet;

/* The body is a plain object now, so scale and rotation go through the style
 * transform properties.  Both take a selector argument that lv_anim's exec
 * callback signature cannot pass, hence the wrappers.
 */

static void pet_set_scale(void *obj, int32_t v)
{
    lv_obj_set_style_transform_scale((lv_obj_t *)obj, v, 0);
}

static void pet_set_rotation(void *obj, int32_t v)
{
    lv_obj_set_style_transform_rotation((lv_obj_t *)obj, v, 0);
}


/* ── Animation helpers ─────────────────────────────────────────── */

static void pet_stop_anims(lv_obj_t *var)
{
    lv_anim_del(var, NULL);
}

/* Reset the pet to its idle pose (no rotation, no offset) */
static void pet_reset_pose(void)
{
    pet_set_scale(s_pet.img, PET_BASE_SCALE);
    pet_set_rotation(s_pet.img, 0);
    lv_obj_set_pos(s_pet.img, s_pet.base_x, s_pet.base_y);
    lv_obj_set_style_opa(s_pet.img, LV_OPA_COVER, 0);
}

/* Generic loop animation: one transform exec, values v1..v2 */
static void pet_loop_anim(lv_obj_t *var, lv_anim_exec_xcb_t exec,
                          int32_t v1, int32_t v2,
                          uint32_t dur, uint32_t playback)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, var);
    lv_anim_set_exec_cb(&a, exec);
    lv_anim_set_values(&a, v1, v2);
    lv_anim_set_time(&a, dur);
    lv_anim_set_playback_duration(&a, playback);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
}

/* lv_obj_set_style_opa() takes a selector arg; wrap for lv_anim exec */
static void pet_set_opa(void *obj, int32_t v)
{
    lv_obj_set_style_opa((lv_obj_t *)obj, (lv_opa_t)v, 0);
}

/* One-shot bounce (scale up then back) */
static void pet_bounce(void)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet.img);
    lv_anim_set_exec_cb(&a, pet_set_scale);
    lv_anim_set_values(&a, PET_BASE_SCALE, 300);
    lv_anim_set_time(&a, 180);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_set_deleted_cb(&a, NULL);
    lv_anim_start(&a);

    lv_anim_t a2;
    lv_anim_init(&a2);
    lv_anim_set_var(&a2, s_pet.img);
    lv_anim_set_exec_cb(&a2, pet_set_scale);
    lv_anim_set_values(&a2, 300, PET_BASE_SCALE);
    lv_anim_set_time(&a2, 320);
    lv_anim_set_delay(&a2, 180);
    lv_anim_set_path_cb(&a2, lv_anim_path_ease_in);
    lv_anim_start(&a2);
}

/* Question marks appear one after another (opacity + rise) */
static void pet_qmark_float_in(void)
{
    lv_obj_t *q = s_pet.qmark;
    lv_obj_set_style_opa(q, LV_OPA_TRANSP, 0);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, q);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&a, s_pet.base_y + QMARK_Y + 14, s_pet.base_y + QMARK_Y);
    lv_anim_set_time(&a, 500);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&a, 500);
    lv_anim_start(&a);

    lv_anim_t o;
    lv_anim_init(&o);
    lv_anim_set_var(&o, q);
    lv_anim_set_exec_cb(&o, pet_set_opa);
    lv_anim_set_values(&o, 0, 255);
    lv_anim_set_time(&o, 400);
    lv_anim_set_repeat_count(&o, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&o, 600);
    lv_anim_start(&o);
}

/* Sparkle pulse */
static void pet_spark_pulse(lv_obj_t *spark)
{
    lv_anim_t o;
    lv_anim_init(&o);
    lv_anim_set_var(&o, spark);
    lv_anim_set_exec_cb(&o, pet_set_opa);
    lv_anim_set_values(&o, 60, 255);
    lv_anim_set_time(&o, 220);
    lv_anim_set_repeat_count(&o, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&o, 220);
    lv_anim_start(&o);
}

/* ── Emotion layers visibility ─────────────────────────────────── */

static void pet_layers_reset(void)
{
    lv_obj_set_style_opa(s_pet.qmark, LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.blush[0], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.blush[1], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.spark[0], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.spark[1], LV_OPA_TRANSP, 0);
    pet_stop_anims(s_pet.qmark);
    pet_stop_anims(s_pet.blush[0]);
    pet_stop_anims(s_pet.blush[1]);
    pet_stop_anims(s_pet.spark[0]);
    pet_stop_anims(s_pet.spark[1]);
}

static void pet_layers_apply(void)
{
    if (!s_pet.layers_visible) {
        return;
    }

    switch (s_pet.emotion) {
    case PET_EMOTION_THINKING:
        pet_qmark_float_in();
        break;
    case PET_EMOTION_CONFUSED:
        lv_obj_set_style_opa(s_pet.qmark, LV_OPA_COVER, 0);
        break;
    case PET_EMOTION_HAPPY:
        lv_obj_set_style_opa(s_pet.blush[0], 200, 0);
        lv_obj_set_style_opa(s_pet.blush[1], 200, 0);
        pet_spark_pulse(s_pet.spark[0]);
        pet_spark_pulse(s_pet.spark[1]);
        break;
    case PET_EMOTION_SPEAKING:
        lv_obj_set_style_opa(s_pet.blush[0], 170, 0);
        lv_obj_set_style_opa(s_pet.blush[1], 170, 0);
        break;
    default:
        break;
    }
}

/* ── Emotion animations ────────────────────────────────────────── */

static void pet_apply_emotion(void)
{
    if (!s_pet.initialized) {
        return;
    }

    pet_stop_anims(s_pet.img);
    pet_layers_reset();
    pet_reset_pose();

    switch (s_pet.emotion) {
    case PET_EMOTION_IDLE:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 7, s_pet.base_y + 7, 1600, 1600);
        break;
    case PET_EMOTION_ACTIVE:
        pet_bounce();
        break;
    case PET_EMOTION_LISTEN:
        pet_loop_anim(s_pet.img, pet_set_rotation,
                      0, 35, 500, 500);
        break;
    case PET_EMOTION_THINKING:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 3, s_pet.base_y + 3, 180, 180);
        break;
    case PET_EMOTION_SPEAKING:
        pet_loop_anim(s_pet.img, pet_set_rotation,
                      0, 40, 260, 260);
        break;
    case PET_EMOTION_HAPPY:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 14, s_pet.base_y + 2, 300, 300);
        break;
    case PET_EMOTION_CONFUSED:
        pet_set_rotation(s_pet.img, -120);  /* -12 degrees tilt */
        break;
    default:
        break;
    }

    pet_layers_apply();
}

/* ── Thread-safe emotion switch ────────────────────────────────── */

typedef struct {
    pet_emotion_t emotion;
} emotion_msg_t;

static void emotion_async_cb(void *data)
{
    emotion_msg_t *msg = (emotion_msg_t *)data;
    s_pet.emotion = msg->emotion;
    pet_apply_emotion();
    free(msg);
}

void pet_display_set_emotion(pet_emotion_t emotion)
{
    emotion_msg_t *msg;

    if (!s_pet.initialized) {
        return;
    }
    if (emotion == s_pet.emotion) {
        return;
    }

    msg = malloc(sizeof(emotion_msg_t));
    if (!msg) {
        return;
    }
    msg->emotion = emotion;
    lv_async_call(emotion_async_cb, msg);
}

pet_emotion_t pet_display_get_emotion(void)
{
    return s_pet.emotion;
}

void pet_display_set_layers_visible(bool visible)
{
    s_pet.layers_visible = visible;
    if (!visible) {
        pet_layers_reset();
    }
}

void pet_display_set_stage_visible(bool visible)
{
    lv_obj_t *objs[6];
    int n = 0;
    int i;

    if (!s_pet.initialized) {
        return;
    }
    if (s_pet.stage_visible == visible) {
        return;
    }
    s_pet.stage_visible = visible;

    objs[n++] = s_pet.img;
    objs[n++] = s_pet.qmark;
    objs[n++] = s_pet.blush[0];
    objs[n++] = s_pet.blush[1];
    objs[n++] = s_pet.spark[0];
    objs[n++] = s_pet.spark[1];

    for (i = 0; i < n; i++) {
        if (!objs[i]) {
            continue;
        }
        if (visible) {
            lv_obj_remove_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
        }
        else {
            /* Kill the animations first: an lv_anim keeps ticking and writing
             * styles on a hidden object, which is pointless work even though
             * the invalidation itself is now culled. */

            lv_anim_delete(objs[i], NULL);
            lv_obj_add_flag(objs[i], LV_OBJ_FLAG_HIDDEN);
        }
    }

    if (visible) {
        /* Re-arm whatever the current emotion asks for. */

        pet_apply_emotion();
    }
}

lv_obj_t *pet_display_get_obj(void)
{
    return s_pet.img;
}

/* ── Init ──────────────────────────────────────────────────────── */

static lv_obj_t *pet_layer_dot(lv_obj_t *screen, int x, int y,
                               uint32_t color, int size)
{
    lv_obj_t *dot = lv_obj_create(screen);
    lv_obj_set_size(dot, size, size);
    lv_obj_set_pos(dot, x, y);
    lv_obj_set_style_radius(dot, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(dot, lv_color_hex(color), 0);
    lv_obj_set_style_bg_opa(dot, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(dot, 0, 0);
    lv_obj_set_style_opa(dot, LV_OPA_TRANSP, 0);
    return dot;
}

/* One rounded bump of the cloud body */
static lv_obj_t *pet_body_bump(lv_obj_t *parent, int x, int y, int size)
{
    lv_obj_t *o = lv_obj_create(parent);
    lv_obj_set_size(o, size, size);
    lv_obj_set_pos(o, x, y);
    lv_obj_set_style_radius(o, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(o, lv_color_hex(0xffffff), 0);
    lv_obj_set_style_bg_opa(o, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(o, 0, 0);
    lv_obj_clear_flag(o, LV_OBJ_FLAG_SCROLLABLE);
    return o;
}

/* Build the cloud mascot out of primitives: a wide rounded body, two bumps
 * on top and two eyes.  Replaces the two 300x300 ARGB8888 frames.
 */
static lv_obj_t *pet_body_create(lv_obj_t *screen)
{
    lv_obj_t *body;
    lv_obj_t *eye;
    int i;

    body = lv_obj_create(screen);
    if (!body) {
        return NULL;
    }
    lv_obj_set_size(body, PET_SIZE, PET_SIZE);
    lv_obj_set_style_bg_opa(body, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(body, 0, 0);
    lv_obj_set_style_pad_all(body, 0, 0);
    lv_obj_clear_flag(body, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_transform_pivot_x(body, PET_PIVOT_X, 0);
    lv_obj_set_style_transform_pivot_y(body, PET_PIVOT_Y, 0);

    /* lower body: wide rounded slab */
    lv_obj_t *slab = lv_obj_create(body);
    lv_obj_set_size(slab, 260, 130);
    lv_obj_set_pos(slab, 20, 130);
    lv_obj_set_style_radius(slab, 65, 0);
    lv_obj_set_style_bg_color(slab, lv_color_hex(0xffffff), 0);
    lv_obj_set_style_bg_opa(slab, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(slab, 0, 0);
    lv_obj_clear_flag(slab, LV_OBJ_FLAG_SCROLLABLE);

    pet_body_bump(body, 55, 95, 105);
    pet_body_bump(body, 145, 70, 130);

    /* eyes */
    for (i = 0; i < 2; i++) {
        eye = lv_obj_create(body);
        lv_obj_set_size(eye, 16, 22);
        lv_obj_set_pos(eye, i == 0 ? 118 : 176, 168);
        lv_obj_set_style_radius(eye, LV_RADIUS_CIRCLE, 0);
        lv_obj_set_style_bg_color(eye, lv_color_hex(0x2b2b2b), 0);
        lv_obj_set_style_bg_opa(eye, LV_OPA_COVER, 0);
        lv_obj_set_style_border_width(eye, 0, 0);
        lv_obj_clear_flag(eye, LV_OBJ_FLAG_SCROLLABLE);
    }

    return body;
}

int pet_display_init(lv_obj_t *screen)
{
    lv_disp_t *disp;
    int W;

    if (s_pet.initialized) {
        return 0;
    }

    disp = lv_display_get_default();
    if (!disp) {
        syslog(LOG_ERR, "[%s] no default display\n", PET_TAG);
        return -EIO;
    }
    W = lv_display_get_horizontal_resolution(disp);

    s_pet.screen = screen;
    s_pet.base_x = (W - PET_SIZE) / 2;
    /* Leave headroom above the pet for the head bubble: keep the pet
     * low enough that bubble (top of screen) and pet do not overlap. */
    s_pet.base_y = lv_display_get_vertical_resolution(disp) / 2 - 120;
    s_pet.emotion = PET_EMOTION_IDLE;
    s_pet.layers_visible = true;
    s_pet.stage_visible = true;

    s_pet.img = pet_body_create(screen);
    if (!s_pet.img) {
        return -ENOMEM;
    }
    pet_set_scale(s_pet.img, PET_BASE_SCALE);
    lv_obj_set_pos(s_pet.img, s_pet.base_x, s_pet.base_y);

    /* Emotion layers */
    s_pet.qmark = lv_label_create(screen);
    lv_label_set_text(s_pet.qmark, "\xef\xbc\x9f\xef\xbc\x9f\xef\xbc\x9f"); /* ？？？ */
    lv_obj_set_style_text_font(s_pet.qmark, &ui_font_cjk_18, 0);
    lv_obj_set_style_text_color(s_pet.qmark, lv_color_hex(0x8fb8ff), 0);
    lv_obj_set_pos(s_pet.qmark, s_pet.base_x + QMARK_X - 40, s_pet.base_y + QMARK_Y);
    lv_obj_set_style_opa(s_pet.qmark, LV_OPA_TRANSP, 0);

    s_pet.blush[0] = pet_layer_dot(screen, s_pet.base_x + BLUSH_X1,
                                   s_pet.base_y + BLUSH_Y, 0xff8fa3, 12);
    s_pet.blush[1] = pet_layer_dot(screen, s_pet.base_x + BLUSH_X2,
                                   s_pet.base_y + BLUSH_Y, 0xff8fa3, 12);
    s_pet.spark[0] = pet_layer_dot(screen, s_pet.base_x + SPARK_X1,
                                   s_pet.base_y + SPARK_Y1, 0xffe08a, 8);
    s_pet.spark[1] = pet_layer_dot(screen, s_pet.base_x + SPARK_X2,
                                   s_pet.base_y + SPARK_Y2, 0xffe08a, 8);

    s_pet.initialized = true;

    pet_apply_emotion();
    syslog(LOG_INFO, "[%s] init OK (%dx%d, pet at %d,%d)\n", PET_TAG,
           (int)lv_display_get_horizontal_resolution(disp),
           (int)lv_display_get_vertical_resolution(disp),
           s_pet.base_x, s_pet.base_y);
    return 0;
}
