/*
 * pet_display.c - Cloud mascot (pet) display module for the AI Agent UI.
 *
 * Renders the cloud bitmap (open/blink frames), emotion layers (question
 * marks, sparkles, blush) and runs the emotion animations with LVGL.
 * All widget access happens on the LVGL thread (callers use the
 * lv_async_call wrapper in pet_display_set_emotion()).
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>

#include "pet_display.h"

/* Generated bitmaps (300x300 ARGB8888) */
extern const uint32_t pet_cloud_open_px[];
extern const uint32_t pet_cloud_blink_px[];

/* Custom CJK subset font (generated by tools/gen_cjk_font.sh) */
extern const lv_font_t ui_font_cjk_18;

#define PET_SIZE       300
#define PET_STRIDE     (PET_SIZE * 4)
#define PET_BASE_SCALE 256    /* LVGL scale: 256 = 100% */
#define PET_PIVOT_X    150
#define PET_PIVOT_Y    285    /* bottom center, so rotation looks natural */
#define BLINK_MS       140    /* blink frame duration */
#define BLINK_PERIOD_MS 3000  /* time between blinks */

/* Emotion layer offsets, relative to the pet top-left corner */
#define QMARK_X        150
#define QMARK_Y        -36
#define BLUSH_X1       105
#define BLUSH_X2       200
#define BLUSH_Y        172
#define SPARK_X1       60
#define SPARK_Y1       -20
#define SPARK_X2       250
#define SPARK_Y2       240

#define PET_TAG "pet"

/* Image descriptors built from the generated pixel arrays */
static const lv_image_dsc_t s_open_dsc = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC,
                .cf = LV_COLOR_FORMAT_ARGB8888,
                .flags = 0,
                .w = PET_SIZE,
                .h = PET_SIZE,
                .stride = PET_STRIDE,
                .reserved_2 = 0 },
    .data_size = PET_SIZE * PET_SIZE * 4,
    .data = (const uint8_t *)pet_cloud_open_px,
    .reserved = NULL,
    .reserved_2 = NULL,
};

static const lv_image_dsc_t s_blink_dsc = {
    .header = { .magic = LV_IMAGE_HEADER_MAGIC,
                .cf = LV_COLOR_FORMAT_ARGB8888,
                .flags = 0,
                .w = PET_SIZE,
                .h = PET_SIZE,
                .stride = PET_STRIDE,
                .reserved_2 = 0 },
    .data_size = PET_SIZE * PET_SIZE * 4,
    .data = (const uint8_t *)pet_cloud_blink_px,
    .reserved = NULL,
    .reserved_2 = NULL,
};

typedef struct {
    bool initialized;
    lv_obj_t *screen;
    lv_obj_t *img;            /* the pet image */
    lv_obj_t *qmark;          /* "？？？" label above the head */
    lv_obj_t *blush[2];       /* pink cheek dots */
    lv_obj_t *spark[2];       /* sparkle dots */
    pet_emotion_t emotion;
    int base_x;               /* pet position when idle */
    int base_y;
    lv_timer_t *blink_timer;
    bool blink_state;         /* false = open, true = blink frame */
    bool layers_visible;
} pet_state_t;

static pet_state_t s_pet;

/* ── Animation helpers ─────────────────────────────────────────── */

static void pet_stop_anims(lv_obj_t *var)
{
    lv_anim_del(var, NULL);
}

/* Reset the pet to its idle pose (no rotation, no offset) */
static void pet_reset_pose(void)
{
    lv_image_set_scale(s_pet.img, PET_BASE_SCALE);
    lv_image_set_rotation(s_pet.img, 0);
    lv_obj_set_pos(s_pet.img, s_pet.base_x, s_pet.base_y);
    lv_obj_set_style_opa(s_pet.img, LV_OPA_COVER, 0);
}

/* Generic loop animation: one transform exec, values v1..v2 */
static void pet_loop_anim(lv_obj_t *var, lv_anim_exec_xcb_t exec,
                          int32_t v1, int32_t v2,
                          uint32_t dur, uint32_t playback)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, var);
    lv_anim_set_exec_cb(&a, exec);
    lv_anim_set_values(&a, v1, v2);
    lv_anim_set_time(&a, dur);
    lv_anim_set_playback_duration(&a, playback);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
}

/* lv_obj_set_style_opa() takes a selector arg; wrap for lv_anim exec */
static void pet_set_opa(void *obj, int32_t v)
{
    lv_obj_set_style_opa((lv_obj_t *)obj, (lv_opa_t)v, 0);
}

/* One-shot bounce (scale up then back) */
static void pet_bounce(void)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet.img);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_image_set_scale);
    lv_anim_set_values(&a, PET_BASE_SCALE, 300);
    lv_anim_set_time(&a, 180);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_set_deleted_cb(&a, NULL);
    lv_anim_start(&a);

    lv_anim_t a2;
    lv_anim_init(&a2);
    lv_anim_set_var(&a2, s_pet.img);
    lv_anim_set_exec_cb(&a2, (lv_anim_exec_xcb_t)lv_image_set_scale);
    lv_anim_set_values(&a2, 300, PET_BASE_SCALE);
    lv_anim_set_time(&a2, 320);
    lv_anim_set_delay(&a2, 180);
    lv_anim_set_path_cb(&a2, lv_anim_path_ease_in);
    lv_anim_start(&a2);
}

/* Question marks appear one after another (opacity + rise) */
static void pet_qmark_float_in(void)
{
    lv_obj_t *q = s_pet.qmark;
    lv_obj_set_style_opa(q, LV_OPA_TRANSP, 0);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, q);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&a, s_pet.base_y + QMARK_Y + 14, s_pet.base_y + QMARK_Y);
    lv_anim_set_time(&a, 500);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&a, 500);
    lv_anim_start(&a);

    lv_anim_t o;
    lv_anim_init(&o);
    lv_anim_set_var(&o, q);
    lv_anim_set_exec_cb(&o, pet_set_opa);
    lv_anim_set_values(&o, 0, 255);
    lv_anim_set_time(&o, 400);
    lv_anim_set_repeat_count(&o, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&o, 600);
    lv_anim_start(&o);
}

/* Sparkle pulse */
static void pet_spark_pulse(lv_obj_t *spark)
{
    lv_anim_t o;
    lv_anim_init(&o);
    lv_anim_set_var(&o, spark);
    lv_anim_set_exec_cb(&o, pet_set_opa);
    lv_anim_set_values(&o, 60, 255);
    lv_anim_set_time(&o, 220);
    lv_anim_set_repeat_count(&o, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_duration(&o, 220);
    lv_anim_start(&o);
}

/* ── Emotion layers visibility ─────────────────────────────────── */

static void pet_layers_reset(void)
{
    lv_obj_set_style_opa(s_pet.qmark, LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.blush[0], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.blush[1], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.spark[0], LV_OPA_TRANSP, 0);
    lv_obj_set_style_opa(s_pet.spark[1], LV_OPA_TRANSP, 0);
    pet_stop_anims(s_pet.qmark);
    pet_stop_anims(s_pet.blush[0]);
    pet_stop_anims(s_pet.blush[1]);
    pet_stop_anims(s_pet.spark[0]);
    pet_stop_anims(s_pet.spark[1]);
}

static void pet_layers_apply(void)
{
    if (!s_pet.layers_visible) {
        return;
    }

    switch (s_pet.emotion) {
    case PET_EMOTION_THINKING:
        pet_qmark_float_in();
        break;
    case PET_EMOTION_CONFUSED:
        lv_obj_set_style_opa(s_pet.qmark, LV_OPA_COVER, 0);
        break;
    case PET_EMOTION_HAPPY:
        lv_obj_set_style_opa(s_pet.blush[0], 200, 0);
        lv_obj_set_style_opa(s_pet.blush[1], 200, 0);
        pet_spark_pulse(s_pet.spark[0]);
        pet_spark_pulse(s_pet.spark[1]);
        break;
    case PET_EMOTION_SPEAKING:
        lv_obj_set_style_opa(s_pet.blush[0], 170, 0);
        lv_obj_set_style_opa(s_pet.blush[1], 170, 0);
        break;
    default:
        break;
    }
}

/* ── Emotion animations ────────────────────────────────────────── */

static void pet_apply_emotion(void)
{
    if (!s_pet.initialized) {
        return;
    }

    pet_stop_anims(s_pet.img);
    pet_layers_reset();
    pet_reset_pose();

    switch (s_pet.emotion) {
    case PET_EMOTION_IDLE:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 7, s_pet.base_y + 7, 1600, 1600);
        break;
    case PET_EMOTION_ACTIVE:
        pet_bounce();
        break;
    case PET_EMOTION_LISTEN:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_image_set_rotation,
                      0, 35, 500, 500);
        break;
    case PET_EMOTION_THINKING:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 3, s_pet.base_y + 3, 180, 180);
        break;
    case PET_EMOTION_SPEAKING:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_image_set_rotation,
                      0, 40, 260, 260);
        break;
    case PET_EMOTION_HAPPY:
        pet_loop_anim(s_pet.img, (lv_anim_exec_xcb_t)lv_obj_set_y,
                      s_pet.base_y - 14, s_pet.base_y + 2, 300, 300);
        break;
    case PET_EMOTION_CONFUSED:
        lv_image_set_rotation(s_pet.img, -120);  /* -12 degrees tilt */
        break;
    default:
        break;
    }

    pet_layers_apply();
}

/* ── Blink timer ───────────────────────────────────────────────── */

static void blink_timer_cb(lv_timer_t *timer)
{
    if (!s_pet.initialized) {
        return;
    }

    if (s_pet.blink_state) {
        /* back to open frame, restore the long period */
        lv_image_set_src(s_pet.img, &s_open_dsc);
        lv_timer_set_period(timer, BLINK_PERIOD_MS);
        s_pet.blink_state = false;
    } else {
        lv_image_set_src(s_pet.img, &s_blink_dsc);
        lv_timer_set_period(timer, BLINK_MS);
        s_pet.blink_state = true;
    }
}

/* ── Thread-safe emotion switch ────────────────────────────────── */

typedef struct {
    pet_emotion_t emotion;
} emotion_msg_t;

static void emotion_async_cb(void *data)
{
    emotion_msg_t *msg = (emotion_msg_t *)data;
    s_pet.emotion = msg->emotion;
    pet_apply_emotion();
    free(msg);
}

void pet_display_set_emotion(pet_emotion_t emotion)
{
    emotion_msg_t *msg;

    if (!s_pet.initialized) {
        return;
    }
    if (emotion == s_pet.emotion) {
        return;
    }

    msg = malloc(sizeof(emotion_msg_t));
    if (!msg) {
        return;
    }
    msg->emotion = emotion;
    lv_async_call(emotion_async_cb, msg);
}

pet_emotion_t pet_display_get_emotion(void)
{
    return s_pet.emotion;
}

void pet_display_set_layers_visible(bool visible)
{
    s_pet.layers_visible = visible;
    if (!visible) {
        pet_layers_reset();
    }
}

lv_obj_t *pet_display_get_obj(void)
{
    return s_pet.img;
}

/* ── Init ──────────────────────────────────────────────────────── */

static lv_obj_t *pet_layer_dot(lv_obj_t *screen, int x, int y,
                               uint32_t color, int size)
{
    lv_obj_t *dot = lv_obj_create(screen);
    lv_obj_set_size(dot, size, size);
    lv_obj_set_pos(dot, x, y);
    lv_obj_set_style_radius(dot, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(dot, lv_color_hex(color), 0);
    lv_obj_set_style_bg_opa(dot, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(dot, 0, 0);
    lv_obj_set_style_opa(dot, LV_OPA_TRANSP, 0);
    return dot;
}

int pet_display_init(lv_obj_t *screen)
{
    lv_disp_t *disp;
    int W;

    if (s_pet.initialized) {
        return 0;
    }

    disp = lv_display_get_default();
    if (!disp) {
        syslog(LOG_ERR, "[%s] no default display\n", PET_TAG);
        return -EIO;
    }
    W = lv_display_get_horizontal_resolution(disp);

    s_pet.screen = screen;
    s_pet.base_x = (W - PET_SIZE) / 2;
    /* Leave headroom above the pet for the head bubble: keep the pet
     * low enough that bubble (top of screen) and pet do not overlap. */
    s_pet.base_y = lv_display_get_vertical_resolution(disp) / 2 - 120;
    s_pet.emotion = PET_EMOTION_IDLE;
    s_pet.layers_visible = true;

    s_pet.img = lv_image_create(screen);
    if (!s_pet.img) {
        return -ENOMEM;
    }
    lv_image_set_src(s_pet.img, &s_open_dsc);
    lv_image_set_pivot(s_pet.img, PET_PIVOT_X, PET_PIVOT_Y);
    lv_image_set_scale(s_pet.img, PET_BASE_SCALE);
    lv_obj_set_pos(s_pet.img, s_pet.base_x, s_pet.base_y);

    /* Emotion layers */
    s_pet.qmark = lv_label_create(screen);
    lv_label_set_text(s_pet.qmark, "\xef\xbc\x9f\xef\xbc\x9f\xef\xbc\x9f"); /* ？？？ */
    lv_obj_set_style_text_font(s_pet.qmark, &ui_font_cjk_18, 0);
    lv_obj_set_style_text_color(s_pet.qmark, lv_color_hex(0x8fb8ff), 0);
    lv_obj_set_pos(s_pet.qmark, s_pet.base_x + QMARK_X - 40, s_pet.base_y + QMARK_Y);
    lv_obj_set_style_opa(s_pet.qmark, LV_OPA_TRANSP, 0);

    s_pet.blush[0] = pet_layer_dot(screen, s_pet.base_x + BLUSH_X1,
                                   s_pet.base_y + BLUSH_Y, 0xff8fa3, 12);
    s_pet.blush[1] = pet_layer_dot(screen, s_pet.base_x + BLUSH_X2,
                                   s_pet.base_y + BLUSH_Y, 0xff8fa3, 12);
    s_pet.spark[0] = pet_layer_dot(screen, s_pet.base_x + SPARK_X1,
                                   s_pet.base_y + SPARK_Y1, 0xffe08a, 8);
    s_pet.spark[1] = pet_layer_dot(screen, s_pet.base_x + SPARK_X2,
                                   s_pet.base_y + SPARK_Y2, 0xffe08a, 8);

    s_pet.blink_timer = lv_timer_create(blink_timer_cb, BLINK_PERIOD_MS, NULL);
    s_pet.initialized = true;

    pet_apply_emotion();
    syslog(LOG_INFO, "[%s] init OK (%dx%d, pet at %d,%d)\n", PET_TAG,
           (int)lv_display_get_horizontal_resolution(disp),
           (int)lv_display_get_vertical_resolution(disp),
           s_pet.base_x, s_pet.base_y);
    return 0;
}
