#!/usr/bin/env python3
"""Generate pet cloud bitmap assets for the ai_agent LVGL UI.

The source PNG already carries an alpha channel (transparent backdrop
with black-outline edges), so the alpha is used as-is.  A blink frame
is synthesized (lids drawn over the eyes in the cloud body color),
and LVGL v9 ARGB8888 C arrays plus preview images are emitted.

Usage: python3 gen_pet_assets.py <input.png> <outdir>
"""

import os
import sys
import numpy as np
from PIL import Image
from scipy import ndimage

SIZE = 300          # target pet size (square)
MIN_EYE_AREA = 60   # min area of an eye blob (at 900x900)
MAX_EYE_AREA = 8000
BG_DARK = (0x1a, 0x1a, 0x2e)  # UI background used for preview


def load(path):
    img = Image.open(path).convert("RGBA")
    a = np.array(img)
    return a[:, :, :3].astype(np.uint8), a[:, :, 3].astype(np.uint8)


def find_eyes(rgb):
    """Locate the two eyes: a pair of round dark blobs (similar area,
    similar row, spaced apart) in the upper part of the image.  The
    cloud's ear is an elongated blob and must NOT match."""
    dark = (rgb[:, :, 0] < 90) & (rgb[:, :, 1] < 90) & (rgb[:, :, 2] < 90)
    lab, n = ndimage.label(dark)
    cands = []
    h, w = dark.shape
    for i in range(1, n + 1):
        mask = lab == i
        area = mask.sum()
        if area < 1000 or area > 3000:
            continue
        ys, xs = np.where(mask)
        bw, bh = xs.max() - xs.min() + 1, ys.max() - ys.min() + 1
        # round-ish blob (not the elongated ear)
        if not (0.7 <= bw / bh <= 1.4):
            continue
        if ys.mean() >= h * 0.7:
            continue
        cands.append((area, xs.mean(), ys.mean(),
                      xs.min(), xs.max(), ys.min(), ys.max()))
    # pair up: similar row + similar area + horizontal spacing
    best = None
    for i in range(len(cands)):
        for j in range(i + 1, len(cands)):
            a1, cx1, cy1, *_ = cands[i]
            a2, cx2, cy2, *_ = cands[j]
            if abs(cy1 - cy2) > 20 or abs(a1 - a2) > max(300, a1 * 0.2):
                continue
            if not (60 < abs(cx1 - cx2) < 250):
                continue
            # keep the pair highest on the face
            if best is None or max(cy1, cy2) < max(best[0][2], best[1][2]):
                best = (cands[i], cands[j])
    return list(best) if best else []


def make_blink(rgb, eyes):
    """Draw closed lids over the eyes: cover the whole eye bounding box
    with the cloud body color, then draw a thin lid line across it."""
    out = rgb.copy()
    h, w, _ = out.shape
    for (_, cx, cy, x0, x1, y0, y1) in eyes:
        sy = min(int(y1) + 6, h - 1)
        body = out[sy, int(cx)]
        # guard against sampling a dark region (e.g. the ear)
        if body.mean() < 150:
            body = (255, 255, 255)
        pad = 3
        xl, xr = max(0, x0 - pad), min(w - 1, x1 + pad)
        yt, yb = max(0, y0 - pad), min(h - 1, y1 + pad)
        out[yt:yb + 1, xl:xr + 1] = body
        # thin closed-lid line at the vertical center
        yc = (y0 + y1) // 2
        out[yc - 1:yc + 2, xl:xr + 1] = (95, 95, 95)
    return out


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    src, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)

    rgb, alpha = load(src)
    h, w = alpha.shape
    print(f"source {w}x{h}, opaque={int((alpha > 250).sum())}, "
          f"transparent={int((alpha == 0).sum())}")

    eyes = find_eyes(rgb)
    print("eyes:", [(int(x0), int(y0), int(x1), int(y1))
                    for _, _, _, x0, x1, y0, y1 in eyes] or "NONE")
    blink_rgb = make_blink(rgb, eyes)

    for tag, src_rgb in (("open", rgb), ("blink", blink_rgb)):
        rgba = np.dstack([src_rgb, alpha])
        pil = Image.fromarray(rgba, "RGBA").resize((SIZE, SIZE), Image.LANCZOS)
        arr = np.array(pil)

        # preview on dark background
        dark = np.full((SIZE, SIZE, 3), BG_DARK, dtype=np.uint8)
        a3 = arr[:, :, 3:4].astype(np.float32) / 255.0
        comp = (arr[:, :, :3].astype(np.float32) * a3 +
                dark.astype(np.float32) * (1.0 - a3)).astype(np.uint8)
        Image.fromarray(comp, "RGB").save(
            os.path.join(outdir, f"preview_{tag}_dark.png"))

        px = arr.reshape(-1, 4)
        u32 = ((px[:, 3].astype(np.uint32) << 24) |
               (px[:, 0].astype(np.uint32) << 16) |
               (px[:, 1].astype(np.uint32) << 8) |
               px[:, 2].astype(np.uint32))
        rows = [
            "#include <stdint.h>",
            "/* Generated by tools/gen_pet_assets.py from "
            + os.path.basename(src) + " */",
            f"/* ARGB8888 {SIZE}x{SIZE}, {len(u32) * 4} bytes */",
            f"const uint32_t pet_cloud_{tag}_px[] = {{",
        ]
        for i in range(0, len(u32), 12):
            rows.append("    " + ", ".join(f"0x{v:08x}" for v in u32[i:i + 12]) + ",")
        rows.append("};")
        cpath = os.path.join(outdir, f"pet_cloud_{tag}.c")
        with open(cpath, "w") as f:
            f.write("\n".join(rows) + "\n")
        print(f"wrote {cpath}")

    print("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
